---
# tasks file for web

- name: check linux distro
  debug: var=ansible_os_family

#- name: update all packages
#  yum:
#    name: '*'
#    state: latest
- name: prepare host before task
  include_task: prepare.yml
  
- name: Install Nginx
  yum:
    name:
      - nginx
    state: latest
    
- name: install php and dependency
  include_task: install-php-dep.yml

- name: create folder /var/www/project.local
  file:
    path: /var/www/project.local
    state: directory
    owner: nginx
    group: nginx
    mode : '0644'

- name: add domain project.local and ssl.progect,local to host file
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1  project.local
      127.0.0.1  ssl.project.local

- name: copy  mysite  
  copy: src=site/ dest=/var/www/project.local/  owner=nginx group=nginx
  notify: reload nginx

- name: copy temlate config php site Vault pass for connect to base
  template: src=dbconfig.php.j2 dest=/var/www/project.local/dbconfig.php owner=nginx group=nginx
  notify: reload nginx
   
- name: copy confi===g nginx
  copy: src=nginx.conf dest={{ destin_nginx_folder }}/nginx.conf  owner=nginx group=nginx
  notify: reload nginx  

#### ssl #######
- name: create folder for ssl
  file:
    path: /etc/ssl/private
    state: directory
    mode: '0700'
- name: copy selfsigned key to /etc/ssl/private
  copy: src=ssl/nginx-selfsigned.key dest=/etc/ssl/private/nginx-selfsigned.key
  notify: reload nginx

- name: copy dhparam.pem to /etc/ssl/certs/
  copy: src=ssl/dhparam.pem  dest=/etc/ssl/certs/dhparam.pem
  notify: reload nginx

- name: copy nginx-selfsigned.crt to /etc/ssl/certs/
  copy: src=ssl/nginx-selfsigned.crt dest=/etc/ssl/certs/nginx-selfsigned.crt
  notify: reload nginx
##### end ssl ####

########### configure php.ini php-fpm  ################

- name: copy template config php-fpm
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf

- name: confguring php.ini
  lineinfile:
    path: /etc/php.ini
    line: cgi.fix_pathinfo=0

############ end php.ini php-fpm  #################

- name: start php-fpm
  service:
      name: php-fpm
      state: started
      enabled: yes


- name: start nginx
  service:
      name: nginx
      state: started
      enabled: yes

- name: test services
  command: systemctl status {{ item }}
  with_items:
    - php-fpm
  register: service_status_php_fpm
- debug: 
    var: service_status_php_fpm 

- name: test services
  command: systemctl status {{ item }}
  with_items:
    - nginx
  register: service_status_nginx
- debug: 
    var: service_status_nginx


- name: check sock
  shell: ls -l /var/run/php-fpm/php-fpm.sock 
  register: sock_info
- debug:
    var: sock_info

- name: check services open ports
  shell: netstat -tlpn
  register: netstat_result

- debug:
    var: netstat_result
 
- name: apply iptables rules for webservers
  include_task: iptables-rules-web.yml
              
