---
- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
    
- name: iptables flush filter
  iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

- name: Ensure SELinux is set to disabled mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: apply turn off selinux without reboot
  shell: setenforce 0