---
# handlers file for nginx
- name: reload nginx
  service: 
    name : nginx
    state: reloaded

- name:  reload php-fpm
  service:
    name : php-fpm
    state: reloaded

- name: reload httpd
  service:
    name: httpd
    state: reloaded

