variables:
    REPO: https://gitlab.com/lightlook/gitlab-ci-1.git
    WORK_DIR: gitlab-ci-1
    NAME_IMGAGE: lightlook/cent-jenk-nginx
    NAME_CONTAINER: cent-jenk-nginx
    BUILD_VERSION: latest
 
  
  stages:
    - build
    - test
    - deploy
  before_script:
    - "rm -rf .git" # clearing .git folder? without this stage had failure
 
  Create image:
    stage: build
    when: manual # run only manual, without automatic run after commits
    tags: 
       - build # tags for my local gitlab_runner
    
      
    script:
      - "rm -rf ~/${WORK_DIR}; mkdir -p ~/${WORK_DIR};  git init; git clone  ${REPO}; cd ${WORK_DIR}; docker build --rm -t ${NAME_IMGAGE}:${BUILD_VERSION} ."
      - "docker run --rm --name ${NAME_CONTAINER} -d -p80:80 -v /opt/jenkins_home:/var/jenkins_home  ${NAME_IMGAGE}:${BUILD_VERSION}"
      
      
  
  Test container:
    stage: test
    when: on_success  # run only if previos stage had success
    tags: 
      - test # tags for my local gitlab_runner
    script:
      - "mkdir -p /opt/jenkins_home/ ; sleep 20;  curl http://localhost | grep -o 'Welcome to Jenkins'"
      - "docker stop ${NAME_CONTAINER}"
      
  
  
      
  # push to docker hub
  Push:  
    stage: deploy
    when: on_success # run only if previos stage had success
    tags: 
      - deploy # tags for my local gitlab_runner
    script: 
      - "docker login -u ${GITHUB_USERNAME} -p ${GITHUB_PASSWORD}"
      - "docker push ${NAME_IMGAGE}:${BUILD_VERSION}"