---
- iptables_raw:
  name: rules
    rules: |
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
          -A INPUT -p all -m state --state ESTABLISHED,RELATED -j ACCEPT
          -A OUTPUT -p all -m state --state ESTABLISHED,RELATED -j ACCEPT
          -A INPUT -p icmp -j ACCEPT

- name: save iptables
  command: iptables-save


    

