---
# tasks file for loadbalancer

#- name: check linux distro
#  debug: var=ansible_os_family

- name: prepare host before task
  import_tasks: prepare.yml

- name: Install dependensies and haproxy
  yum:
    name:
      - deltarpm
      - haproxy
    state: latest

- name: copy config haproxy
  template: src=haproxy.cfg.j2 dest={{ destin_haproxy_folder }}/haproxy.cfg owner=haproxy group=haproxy
  notify: reload haproxy


- name: start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes

