---
# tasks file for base_db
- name: ping servers
  ping:

- name: check linux distro
  debug: var=ansible_os_family

#- name: update all packages
#  yum:
#    name: '*'
#    state: latest

- name: iptables flush filter
  iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

- name: save rules iptables
  shell: /sbin/iptables-save  > /etc/sysconfig/iptables

- name: Ensure SELinux is set to disabled mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: apply turn off selinux without reboot
  shell: setenforce 0


- name: install mariadb and dependecy
  yum:
    name:
      - mariadb 
      - mariadb-server 
      - net-tools
      - python
      - python-pip
      - MySQL-python
    state: latest

- name: pip upgrade
  shell: pip install --upgrade pip

#- name: install MySQLdb
#  shell: pip install  --user  MySQLdb

#- name: install  PyMySQL
#  shell: pip3 install  --user PyMySQL 
#- pip:
#    name:  PyMySQL
#    executable: pip-3.3
- name: disable strict sql
  blockinfile:
    path: /etc/mysql/conf.d/disable_strict_mode.cnf
    block: |
      [mysqld]
      sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    create: yes
  notify: restart mariadb

- name: start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Copy database dump file
  copy:
    src: sql/dbpdo.sql
    dest: /tmp

#- name: Create a new database
#  mysql_db:
#    name: "{{ dbname }}"
#    state: present

- name: Restore database
  mysql_db:
    name: "{{ dbname }}"
    state: import
    target: /tmp/dbpdo.sql

- name: Create database user  with name 'dppdo@'%'' and password 'dppdo' with all database privileges
  mysql_user:
    name: "{{ dbuser }}"
    host: "%"
    password: "{{ dbpass }}"
    priv: '*.*:ALL'
    state: present

- name: Create database user  with name 'dppdo@localhost' and password 'dppdo' with all database privileges
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv: '*.*:ALL'
    state: present


                      
                                                 
