---
# tasks file for base_db
- name: check linux distro
  debug: var=ansible_os_family

#- name: update all packages
#  yum:
#    name: '*'
#    state: latest

- name: prepare host before task
  include_task: prepare.yml

- name: install mariadb and dependecy
  yum:
    name:
      - mariadb 
      - mariadb-server 
      - net-tools
 
    state: latest

- name: install Python and dependensy
  include_task: install-py-depend.yml

- name: start mariadb
  service:
    name   : mariadb
    state  : started
    enabled: yes

- name: Copy database dump file
  copy:
    src : sql/dbpdo.sql
    dest: /tmp

- name: Create a new database
  mysql_db:
    name  : "{{ dbname }}"
    state : present
    
- name: Create database user  with name 'dppdo@'%'' and VAULT password  with all database privileges
  mysql_user:
    name    : "{{ dbuser }}"
    host    : "%"
    password: "{{ dbpass }}"
    priv    : '{{ dbname }}.*:ALL'
    state   : present
  
- name: Create database user  with name 'dppdo@localhost' and VAULT password  with all database privileges
  mysql_user:
    name    : "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv    : '{{ dbname }}.*:ALL'
    state   : present
    
- name: Restore database from user dppdo@'%
  mysql_db:
    login_user    : "{{ dbuser }}"
    login_password: "{{ dbpass }}"
    name          : "{{ dbname }}"
    state         : import
    target        : /tmp/dbpdo.sql



- name: apply iptables rules for base_db
  include_task: iptables-rules-db.yml



                      
                                                 
