version: "3"
services:

    nginx:
        image: nginx:1.13
        ports:
          - "80"
        restart: always

        ports:
          - 8081:80

        volumes:
          - ./nginx:/usr/share/nginx/html
        networks:
          - back-tier
    apache:
        image: httpd:2.4
        restart: always


        ports:
          - 8082:80
        volumes:
          - ./apache:/usr/local/apache2/htdocs
        networks:
          - back-tier

    lb:

        image: dockercloud/haproxy
        links:
          - nginx
          - apache
        ports:
          - "80:80"
        restart: always
        networks:
          - front-tier
          - back-tier
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock


networks:
    front-tier:
        driver: bridge
    back-tier:
        driver: bridge
